# SQL Cleanser - Application Settings
# Configuration for core application behavior

application:
  name: "SQL Cleanser"
  version: "1.0.0"
  description: "AI-Powered PostgreSQL to Oracle SQL Migration Tool"

server:
  host: "0.0.0.0"
  port: 8000
  debug: false
  cors_enabled: true
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:5173"

processing:
  max_file_size_mb: 100
  max_files_per_upload: 50
  temp_dir: "src/backend/jobs"
  cleanup_after_hours: 24

  # AI Processing Settings
  ai_timeout_seconds: 60
  ai_fallback_enabled: true
  max_sample_rows_for_analysis: 10

ollama:
  host: "http://localhost:11434"
  model: "llama3:8b"
  max_tokens: 512
  timeout_seconds: 30

database:
  # Future database integration settings
  enabled: false
  connection_string: ""

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_rotation: true
  max_log_size_mb: 10
  backup_count: 5

security:
  max_request_size_mb: 200
  rate_limiting:
    enabled: true
    requests_per_minute: 60
